import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
	container: {
		flex: 0.9,
		marginTop: 50,
		justifyContent: "center",
		alignItems: "center",
	},
	image: {
		width: 120,
		height: 120,
		resizeMode: "contain",
		marginBottom: 80,
	},
	loginBox: {
		flexDirection: "row",
		alignItems: "center",
		borderWidth: 1,
		borderColor: "white",
		borderRadius: 10,
		paddingHorizontal: 20,
		marginBottom: 15,
		width: 250,
		height: 50,
	},
	label: {
		color: "white",
		fontSize: 16,
		width: 70,
	},

	loginInput: {
		flex: 1,
		color: "white",
		borderBottomWidth: 1,
		borderColor: "white",
		paddingVertical: 4,
	},

	buttonText: {
		color: "white",
		fontSize: 18,
		marginTop: 10,
	},

	mainProfileimage: {
		width: 55,
		height: 55,
		borderRadius: 100,
		shadowColor: "white",
		opacity: 0.5,
	},
	headerContainer: {
		position: "absolute",
		top: 90,
		right: 20,
		zIndex: 10,
	},
	row: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "flex-end",
	},
	subProfileImg: {
		width: 50,
		height: 50,
		borderRadius: 25,
		shadowColor: "white",
		opacity: 0.3,
		borderWidth: 2,
		borderColor: "#ffffff5d",
	},
	mainImage: {
		width: 200,
		height: 200,
		paddingTop: 0,
		marginTop: 80,
		marginBottom: 40,
		borderRadius: 100,
		shadowColor: "green",
		borderWidth: 1,
		borderColor: "rgb(255, 255, 255)",
	},
	mainName: {
		color: "white",
		fontSize: 26,
		fontWeight: 800,
		marginBottom: 40,
	},
	mainChat: {
		backgroundColor: "rgb(47 57 67)",
		paddingTop: 20,
		paddingBottom: 20,
		width: 330,
		border: 1,
		marginBottom: 60,
		borderRadius: 15,
		textAlign: "center",
		color: "white",
		fontSize: 22,
	},
	mainText: {
		color: "white",
		fontSize: 24,
		fontWeight: "bold",
		marginBottom: 10,
		textAlign: "center",
	},
	chatBox: {
		marginTop: 20,
		width: "80%",
		height: 50,
		paddingTop: 8,
		justifyContent: "center",
		backgroundColor: "rgba(125, 125, 125, 0.15)",
		borderRadius: 10,
	},
	chatText: {
		color: "white",
		fontSize: 20,
		fontWeight: "bold",
		marginBottom: 10,
		textAlign: "center",
	},

	buttonWrapper: {
		width: 120,
		height: 120,
		marginTop: 30,
	},
	phoneImage: {
		width: 100,
		height: 100,
		resizeMode: "contain",
	},
	touchArea: {
		width: 105,
		height: 105,
		borderRadius: 60,
		backgroundColor: "rgba(125, 125, 125, 0.4)",
		justifyContent: "center",
		alignItems: "center",
	},
});
